name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare env file
      run: |
        cp .env.dist .env
        cp docker.env.dist docker.env

    - name: Build the Docker image
      run: docker-compose build
